### ISSUE TITLE
AJ tests that need redis are skipped?

### ISSUE THREAD

**Issue by BrentWheeldon** [rails/rails-dev-box#142]
Hi there,

When I run `bundle exec rake test:integration:resque` from the `activejob` directory I get:

```
/usr/bin/ruby2.4 -I"lib:test" -I"/var/lib/gems/2.4.0/gems/rake-12.2.1/lib" "/var/lib/gems/2.4.0/gems/rake-12.2.1/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using resque


*** rake aj:integration:resque ***
Cannot run integration tests for resque. To be able to run integration tests for resque you need to install and start redis.
```

Redis is running:

```
ubuntu@rails-dev-box:/vagrant/rails/activejob$$ ps aux | grep redis
ubuntu    6280  0.0  0.0  12960   932 pts/0    S+   19:54   0:00 grep --color=auto redis
redis     8426  0.0  0.4  37364  9180 ?        Ssl  19:25   0:01 /usr/bin/redis-server 127.0.0.1:6379
```

If I edit the URL in [`activejob/test/support/integration/adapters/resque.rb:6`](https://github.com/rails/rails/blob/master/activejob/test/support/integration/adapters/resque.rb#L6) to just be `"redis://127.0.0.1:6379/12"` it works.

Is there some extra config I need to make this work without having to edit the test helper?

**Comment by yahonda** [comment]
Hi, I attempted to reproduce it but `bundle exec rake test:integration:resque` finishes successfully without modify the URL.


```ruby
ubuntu@rails-dev-box:~$ git clone https://github.com/rails/rails.git
ubuntu@rails-dev-box:~$ cd rails/activejob/
ubuntu@rails-dev-box:~/rails/activejob$ bundle
ubuntu@rails-dev-box:~/rails/activejob$ bundle exec rake test:integration:resque
/usr/bin/ruby2.4 -I"lib:test" -I"/var/lib/gems/2.4.0/gems/rake-12.2.1/lib" "/var/lib/gems/2.4.0/gems/rake-12.2.1/lib/rake/rake_test_loader.rb" "test/integration/queuing_test.rb"
Using resque


*** rake aj:integration:resque ***
/tmp/d20171117-5343-738e3l/dummy/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /tmp/d20171117-5343-738e3l/dummy/config/application.rb to limit the frameworks that will be loaded.
Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /var/lib/gems/2.4.0/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')Run options: --seed 21776

# Running:


Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /var/lib/gems/2.4.0/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing').SS
The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /var/lib/gems/2.4.0/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing').
The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
.The client method is deprecated as of redis-rb 4.0.0, please use the new _clientmethod instead. Support for the old method will be removed in redis-namespace 2.0.
.SS..S

Finished in 13.852572s, 0.7941 runs/s, 0.5775 assertions/s.
11 runs, 8 assertions, 0 failures, 0 errors, 5 skips

You have skipped tests. Run with --verbose for details.
ubuntu@rails-dev-box:~/rails/activejob$
```

**Comment by BrentWheeldon** [comment]
@yahonda Huh - it's totally working for me now, too. I have no idea what I was doing wrong, but that's for confirming it wasn't an issue for other folks.

Sorry for the false alarm!

**Comment by fxn** [comment]
No prob, thanks for the heads up!
